---
- name: Check connectivity to remote servers
  hosts: localhost #servergroup01
  gather_facts: True
  tasks:
    - name: ping
      ping:
    - name: Print all available facts
      debug:
        var: ansible_facts
    - name: Print all available facts01
      debug:
        var: ansible_facts['env']['VMWARE_HOST']
    - name: Print all available facts02
      debug:
        var: ansible_local
